shapediver/AppBuilderSdk

package-lock.json
package.json
src/App.tsx
src/components/shapediver/exports/ExportButtonComponent.tsx
src/components/shapediver/parameter/ParameterBooleanComponent.tsx
src/components/shapediver/parameter/ParameterColorComponent.tsx
src/components/shapediver/parameter/ParameterFileInputComponent.tsx
src/components/shapediver/parameter/ParameterLabelComponent.tsx
src/components/shapediver/parameter/ParameterSelectComponent.tsx
src/components/shapediver/parameter/ParameterStringComponent.tsx
src/components/shapediver/ui/ParametersAndExportsAccordionComponent.tsx
src/components/shapediver/viewport/ViewportIcons.tsx
src/components/ui/HeaderBar.tsx
src/components/ui/ModelSelect.tsx
src/components/ui/NavigationBar.tsx
src/hooks/useMantineBranding.ts
src/hooks/useParameterChanges.ts
src/hooks/useSession.ts
src/hooks/useSortedParametersAndExports.ts
src/pages/ExamplePage.tsx
src/pages/HomePage.tsx
src/pages/MultipleViewportPage.tsx
src/pages/NoMatchPage.tsx
src/pages/ViewPage.tsx
src/store/useShapeDiverStoreParameters.ts
src/types/shapediver/parameter.ts
src/types/store/shapediverStoreParameters.ts

I extended the code of the abstracted parameters, such that parameter changes can get queued before they are executed. However, there is no UI yet which would allow the user to accept or reject the changes.

prepare commit mode for parameters

---

src/components/shapediver/viewport/ViewportIcons.tsx

https://shapediver.atlassian.net/browse/SS-7153

SS-7153: Add AR QR code

---

src/components/shapediver/ui/ParametersAndExportsAccordionComponent.module.css
src/components/shapediver/ui/ParametersAndExportsAccordionComponent.tsx
src/components/shapediver/ui/ParametersAndExportsAccordionTab.module.css
src/components/shapediver/ui/ParametersAndExportsAccordionTab.tsx
src/components/shapediver/viewport/ViewportComponent.module.css
src/components/ui/ModelSelect.tsx
src/hooks/useIsLandscape.ts
src/pages/CustomUiPage.module.css
src/pages/CustomUiPage.tsx
src/pages/ExamplePage.module.css
src/pages/ExamplePage.tsx
src/pages/MultipleViewportPage.module.css
src/pages/MultipleViewportPage.tsx
src/pages/ViewPage.module.css
src/pages/ViewPage.tsx

@snabela the "absolute" position generates too many unpredictable issues. 
( e.g. open the select list at the https://react-example.shapediver.com/prod/#/modelSelect )
So, I get rid from it and also get rid from aside to control the layout via css Grid system.

SS-7177: Refactor root layout

---

src/hooks/useSessionWithWebApp.ts
src/pages/CustomUiPage.tsx
src/pages/MultipleViewportPage.tsx
src/pages/ViewPage.tsx

https://shapediver.atlassian.net/browse/SS-7332

SS-7332 Schema for web app data output

---

src/components/shapediver/ui/TextWidgetComponent.tsx

https://shapediver.atlassian.net/browse/SS-7381

SS-7381: Apply mantine components to the markdown

---

src/components/shapediver/viewport/ViewportIcons.tsx

https://shapediver.atlassian.net/browse/SS-7391

SS-7391: Close popup on alert close

---

package-lock.json
package.json
src/components/shapediver/ui/MarkdownWidgetComponent.tsx
src/pages/appbuilder/AppBuilderStaticExamplePage.tsx

@LemToUp please see task https://shapediver.atlassian.net/browse/SS-7445 and continue this PR.

SS-7445 markdown text coloring wip

---

src/components/shapediver/ui/MarkdownWidgetComponent.tsx
src/components/shapediver/ui/ParametersAndExportsAccordionComponent.tsx
src/components/ui/TabsComponent.tsx
src/pages/HomePage.tsx
src/pages/appbuilder/AppBuilderPage.tsx
src/types/components/shapediver/componentTypes.ts

https://shapediver.atlassian.net/browse/SS-7446

SS-7446: Fix types

---

.gitignore
README.md
package-lock.json
package.json
scripts/build-appbuilder.sh
src/AppBuilderRoot.tsx
src/ExampleRoot.tsx

https://shapediver.atlassian.net/browse/SS-7403

SS-7403 Set up appbuilder.shapediver.com

---

src/hooks/ui/useCustomTheme.ts
src/pages/templates/AppBuilderGridTemplatePage.tsx
src/pages/templates/ExampleTemplatePage.tsx

https://shapediver.atlassian.net/browse/SS-7475

SS-7475 fix background color for fullscreen mode

---

public/iframe4.json
src/components/shapediver/appbuilder/AppBuilderAccordionWidgetComponent.tsx
src/components/shapediver/appbuilder/AppBuilderFallbackContainerComponent.tsx
src/components/shapediver/appbuilder/AppBuilderImageExportWidgetComponent.tsx
src/components/shapediver/appbuilder/AppBuilderTabsComponent.tsx
src/components/ui/ModelSelect.tsx
src/hooks/shapediver/useSessionWithAppBuilder.ts
src/pages/appbuilder/AppBuilderPage.tsx
src/pages/examples/CustomUiPage.tsx
src/pages/examples/MultipleViewportPage.tsx
src/pages/examples/ViewPage.tsx
src/store/useShapeDiverStoreParameters.ts
src/types/store/shapediverStoreParameters.ts

https://shapediver.atlassian.net/browse/SS-7441

SS-7441 Request computation and exports at once

---

package.json
scripts/build-appbuilder-platform.sh
src/hooks/shapediver/useAppBuilderSettings.ts
src/hooks/shapediver/useResolveAppBuilderSettings.ts
src/types/shapediver/appbuilder.ts

https://shapediver.atlassian.net/browse/SS-7481

SS-7481 appbuilder embedded in platform

---

package.json
public/iframe5.json
public/iframe6.json
src/hooks/shapediver/useAppBuilderSettings.ts
src/hooks/ui/useCustomTheme.ts
src/store/useThemeOverrideStore.ts
src/types/shapediver/appbuilder.ts
src/types/shapediver/appbuildertypecheck.ts

https://shapediver.atlassian.net/browse/SS-7516

SS-7516 Allow theme overrides from AppBuilder settings json file 

---

public/iframe8.json
src/components/shapediver/appbuilder/AppBuilderImage.tsx
src/components/shapediver/appbuilder/AppBuilderImageExportWidgetComponent.tsx
src/components/shapediver/appbuilder/AppBuilderImageWidgetComponent.tsx
src/types/shapediver/appbuilder.ts
src/types/shapediver/appbuildertypecheck.ts

https://shapediver.atlassian.net/browse/SS-7556

SS-7556: Add the Anchor to images

---

package-lock.json
package.json
src/components/shapediver/ui/MarkdownWidgetComponent.tsx
src/pages/appbuilder/AppBuilderStaticExamplePage.tsx

https://shapediver.atlassian.net/browse/SS-7498

SS-7498: Add markdown table support

---

src/components/shapediver/parameter/ParameterFileInputComponent.tsx
src/store/useShapeDiverStoreParameters.ts

reproduced the logic we use on the platform frontend for files which miss a type defined by the OS

SS-7587 guess missing File MIME type

---

src/hooks/shapediver/useResolveAppBuilderSettings.ts

https://shapediver.atlassian.net/browse/SS-7572

SS-7572: Add redirect on model init error

---

README.md
public/customTheme1.json
public/customTheme2.json
public/perforationswall.json
src/components/shapediver/ui/MarkdownWidgetComponent.tsx
src/hooks/shapediver/appbuilder/useAppBuilderSettings.ts
src/hooks/shapediver/appbuilder/useResolveAppBuilderSettings.ts
src/hooks/shapediver/appbuilder/useSessionWithAppBuilder.ts
src/hooks/shapediver/useSessionWithCustomUi.ts
src/hooks/ui/useCustomTheme.ts
src/pages/appbuilder/AppBuilderPage.tsx
src/pages/appbuilder/AppBuilderStaticExamplePage.tsx
src/pages/examples/CustomUiPage.tsx
src/pages/examples/ViewPage.tsx
src/pages/misc/LoaderPage.tsx
src/types/shapediver/appbuilder.ts

Please see https://shapediver.atlassian.net/browse/SS-7593?focusedCommentId=25021

SS-7593 improved landing page

---

src/components/shapediver/parameter/ParameterSelectComponent.tsx
src/hooks/shapediver/parameters/useParameterComponentCommons.ts

https://shapediver.atlassian.net/browse/SS-7598

SS-7598: Add parameter select multiple support

---

public/iframe2.json
src/components/shapediver/appbuilder/AppBuilderAccordionWidgetComponent.tsx
src/components/shapediver/appbuilder/AppBuilderImageExportWidgetComponent.tsx
src/components/shapediver/exports/ExportButtonComponent.tsx
src/components/shapediver/exports/ExportLabelComponent.tsx
src/components/shapediver/parameter/ParameterLabelComponent.tsx
src/components/shapediver/ui/ParametersAndExportsAccordionComponent.tsx
src/hooks/shapediver/parameters/useExport.ts
src/hooks/shapediver/parameters/useParameter.ts
src/hooks/shapediver/parameters/useParameterComponentCommons.ts
src/hooks/shapediver/parameters/useSortedParametersAndExports.ts
src/store/useShapeDiverStoreParameters.ts
src/types/components/shapediver/propsExport.ts
src/types/components/shapediver/propsParameter.ts
src/types/shapediver/appbuilder.ts
src/types/shapediver/appbuildertypecheck.ts
src/types/shapediver/common.ts
src/types/store/shapediverStoreParameters.ts

https://shapediver.atlassian.net/browse/SS-7683
The included example can be tested locally using http://localhost:3000/?g=iframe2.json

SS-7683 overriding of parameter/export properties

---

public/iframe11.json
src/hooks/shapediver/appbuilder/useAppBuilderCustomParameters.ts
src/hooks/shapediver/appbuilder/useSessionWithAppBuilder.ts
src/hooks/shapediver/parameters/useDefineGenericParameters.ts
src/hooks/shapediver/parameters/useSortedParametersAndExports.ts
src/store/useShapeDiverStoreParameters.ts
src/types/store/shapediverStoreParameters.ts

https://shapediver.atlassian.net/browse/SS-7484

SS-7484 register custom parameters

---

package-lock.json
package.json
src/AppBuilderBase.tsx
src/ExampleBase.tsx

https://shapediver.atlassian.net/browse/SS-7728
Already works, I tested it by putting an example code in the ViewPage.

SS-7728: implemented notification framework

---

public/iframe13.json

https://shapediver.atlassian.net/browse/SS-7396

SS-7396 App Builder actions

---

src/pages/examples/AppBuilderStaticExamplePage.tsx
src/pages/examples/ViewPage.tsx

https://shapediver.atlassian.net/browse/SS-8129
please review together with https://github.com/shapediver/AppBuilderShared/pull/35

SS-8129: renaming of sessionId an usage of sessionDependencies

---

package.json
pnpm-lock.yaml

https://github.com/tabler/tabler-icons/issues/1233

Rollback issued package

---

package.json
pnpm-lock.yaml
public/example-agent-bookshelf-2.json
public/example-agent-bookshelf.json
scripts/build-appbuilder-platform.sh
scripts/build-appbuilder.sh
vite.config.ts

Related PR in `AppBuilderShared` repository: https://github.com/shapediver/AppBuilderShared/pull/73

SS-8371 AI Agent WIP
